<?php
/*     Filename    footing.inc 
 *                 Contains the page formating type stuff and also
 *                 the line of links to the other important pages
 *                 ooh and also statcounter stuff
 */

echo '<!-- Start of StatCounter Code for Default Guide -->';
echo '<script type="text/javascript">';
echo 'var sc_project=8393916; ';
echo 'var sc_invisible=1; ';
echo 'var sc_security="0e12c866"; ';
echo '</script>';
echo '<script type="text/javascript"';
echo 'src="http://www.statcounter.com/counter/counter.js"></script>';
echo '<noscript><div class="statcounter"><a title="hits counter"';
echo 'href="http://statcounter.com/free-hit-counter/"';
echo 'target="_blank"><img class="statcounter"';
echo 'src="http://c.statcounter.com/8393916/0/0e12c866/0/"';
echo 'alt="hits counter"></a></div></noscript>';
echo '<!-- End of StatCounter Code for Default Guide -->';

echo "</body></html>";

?>